=== jtarrias/ejerciciosprogramacion/lgmsi/src/lgmsi/02_correoselectronicos.dtd
<!ELEMENT	emails (email*)>
  <!ELEMENT emails (para, cc, cco, asunto, cuerpo, adjunto)>
  
  <!ELEMENT para (#PCDATA)>
  <!ELEMENT cc (#PCDATA)>
  <!ELEMENT cco (#PCDATA)>
  <!ELEMENT asunto (#PCDATA)>
  <!ELEMENT cuerpo (#PCDATA)>
  <!ELEMENT adjunto (nombre, mine-type, longitud)>
  <!ELEMENT nombre (#PCDATA)>
  <!ELEMENT mine-type (#PCDATA)>
  <!ELEMENT longitud (#PCDATA)>

=== jtarrias/ejerciciosprogramacion/lgmsi/src/lgmsi/02_correoselectronicos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE emails SYSTEM	"02_correoselectronicos.dtd">
<emails>
	<email>
		<para>perico@gmail.com</para>
		<cco>lucas@gjhjs.com</cco>
		<asunto></asunto>
		<cuerpo></cuerpo>
		<adjunto>
			<nombre></nombre>
			<mine-type>image/jpeg</mine-type>
			<lomgitud></lomgitud>
	    </adjunto>
	</email>
</emails>
